### ISSUE TITLE
oxmysql: TypeError

### ISSUE THREAD

**Issue by marksman717** [DokusCore/Server-Prebuild#3]
Hello,

first off i would like to that you for the server prebuild!

i am having a problem and was hoping you might know what it is.

I keep getting this error when i start the server 

" script:oxmysql] [0m[0mError loading script oxmysql.js in resource oxmysql: TypeError: Unknown charset '0r392gk6ja'"

**Comment by DevDokus** [comment]
Hey @marksman717 
The charset the database uses is **utf8mb4**.
The charset you are trying to set is not accepted.

**Comment by marksman717** [comment]
thank you for the info! is there anyway i can fix it or is it simply my DDB that wont work with this script?

**Comment by DevDokus** [comment]
I am not sure when you get this problem, where it originates from and what you did just before that to receive this error. We are not using any other charset then utf8, so not sure where that error relates to or how you got that in the first place.
